# -*- coding: utf-8 -*-
"""if

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aKkbpOa_wyBEgikq-O7b-xRKu0JrxDpj
"""

a = int(input('your num:'))
if a >= 0:
  v = a + 1
  print(v)
else:
  print(a)

a = int(input('your num:'))
if a >= 0:
  v = a + 1
  print(v)
else:
  c = a - 2
  print(c)

a = int(input('your num:'))
if a > 0:
  v = a + 1
  print(v)
elif a == 0:
  a = 10
  print(a)
elif a < 0:
  c = a - 2
  print(c)

a = int(input('your num:'))
b = int(input('your num:'))
c = int(input('your num:'))
n = 0
if a > 0:
  n += 1
if b > 0:
  n += 1
if c > 0:
  n += 1

print(n)

a = int(input('your num:'))
b = int(input('your num:'))
c = int(input('your num:'))
n = 0
if a > 0:
  n += 1
if b > 0:
  n += 1
if c > 0:
  n += 1
print(n)

n = 0
if a < 0:
  n += 1
if b < 0:
  n += 1
if c < 0:
  n += 1

print(n)

a = int(input('your num:'))
b = int(input('your num:'))
if a > b:
  print(a)
else:
  print(b)

a = int(input('your num:'))
b = int(input('your num:'))
if a > b:
  print(1)
else:
  print(2)

a = int(input('your num:'))
b = int(input('your num:'))
if a > b:
  print(a, b)
else:
  print(b, a)

a = int(input('your num:'))
b = int(input('your num:'))
if a > b:
  a, b = b, a
print(a,b)

a = int(input('your num:'))
b = int(input('your num:'))
if a == b:
  a = 0
  b = 0
  print(a, b)
else:
  print(a, b)

a = int(input('your num:'))
b = int(input('your num:'))
if a != b:
  maxi = max(a, b)
  a = maxi
  b = maxi
else:
  a = 0
  b = 0
print(a, b)

a = int(input('your num:'))
b = int(input('your num:'))
m = int(input('your num:'))
if a < b and a < m:
  print(a)
elif b < a and b < m:
  print(b)
elif m < a and m < b:
  print(m)

"""If13. Даны три числа. Найти среднее из них (то есть число, расположенное
между наименьшим и наибольшим).
"""

a = int(input('your num: '))
b = int(input('your num: '))
c = int(input('your num: '))

if (b <= a <= c) or (c <= a <= b):
    print(a)
elif (a <= b <= c) or (c <= b <= a):
    print(b)
else:
    print(c)

"""If14. Даны три числа. Вывести вначале наименьшее, а затем наибольшее из
данных чисел.
"""

a = int(input('your num: '))
b = int(input('your num: '))
c = int(input('your num: '))
if