# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xOigeN14sXDMSgzSJJEqfOzR0-OrWhqQ
"""

people = ['Tom', 'Sam', 'Bob']
print(people[0])
print(people[1])
print(people[2])

print(people[-2])
print(people[-1])
print(people[-3])

people = ['Tom', 'Sam', 'Bob']
for person in people:
  print(person)

people = ['Tom', 'Sam', 'Bob']
i = 0
while i <= len (people):
  print(people[i])
  i += 1

people = ['Tom', 'Bob', 'Sam', ',kf', 'jhg']
slice_people1 = people[:3]
print(slice_people1)

slice_people2 = people[1:3]
print(slice_people2)
slice_people3 = people[1:6:2]
print(slice_people3)

