# -*- coding: utf-8 -*-
"""Копия блокнота "game"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kjhXN9wK54yLolzmGEJ5UOmVpzIiXp7c

# Задание 1. Камень, Ножницы, Бумага (на победу)
### Суть: Классическая игра против компьютера, но с условием: играть нужно до 3-х побед.
Основные требования:
1. Компьютер случайным образом выбирает один из трех вариантов.
2. Игрок вводит свой вариант
3. Вывод результата раунда (Победа / Поражение / Ничья) и общего счета.
4. Игра идет в цикле, пока кто-то не наберет 3 очка.
5. В конце предложение сыграть еще раз.
"""

import random

# Ваше решение здесь
score = 0
while True:
  a = random.randint(1, 3)
  b = int(input('your num:'))
  if a == 1 and b == 2:
    print(a, 'you lose')
  elif a == b:
    print(a, 'nitya')
  elif a == 2 and b == 3:
    print(a, 'you lose')
  elif a == b:
    print(a, 'nitya')
  elif a == 3 and b == 1:
    print(a, 'you lose')
  elif a == b:
    print(a, 'nitya')
  elif a == 2 and b == 1:
    print(a, 'you win')
    score += 1
    print('wins:', score)
  elif a == 3 and b == 2:
    print(a, 'you win')
    score += 1
    print('wins:', score)
  elif a == 1 and b == 3:
    print(a, 'you win')
    score += 1
    print('wins:', score)
  if score == 3:
    break

"""# Задание 2. Виселица (Угадай слово)
### Суть: Игрок угадывает скрытое слово, называя буквы. За каждую ошибку отнимается «жизнь».
Основные требования:
1. Заранее подготовленный массив/список слов. Случайный выбор одного.
2. Слово отображается в виде прочерков или нижних подчеркиваний (например: _ _ _ _ _).
3. При вводе буквы программа проверяет, есть ли она в слове. Если да — открывает все такие буквы. Если нет — вычитает жизнь.
4. Вывод сообщения о победе или поражении.

"""

# Ваше решение здесь

import random

secret_word = random.choice(["питон", "слово", "игра", "код"])
guessed = ""
lives = 6

while lives > 0:
    display = "".join([letter if letter in guessed else " _" for letter in secret_word])
    print(f"\nСлово: {display} | Жизней: {lives}")

    if "_" not in display:
        print("Вы победили!")
        break

    char = input("Буква: ").lower()
    guessed += char

    if char not in secret_word:
        lives -= 1
else:
    print("Вы проиграли! Было загадано:", secret_word)

"""# Задание 3. Угадай число
### Суть: Программа загадывает число от 1 до 100. Пользователь пытается угадать это число.
Основные требования:
1. После попытки угадать программа сообщает один из вариантов:
  - Не угадал! Загаданное число БОЛЬШЕ
  - Не угадал! Загаданное число МЕНЬШЕ
  - Поздравляем ты угадал число!
2. Программа считает количество неудачных попыток и выводит счет в конце игры.
3. \* Улучшите игру так чтобы пользователь мог сам указывать диапазон загаднного числа. Диапазон не должен быть меньше 10. И не должен быть отрицательным.
4. \** Определить минимальное необходимое число попыток для нахождения загаданного числа. Если пользователь не укладывается в это количество попыток - то он проигрывает. (Задача учитывается только при выполнении пункта 3.
"""

# Ваше решение здесь

import random
pc = random.randint(1, 100)
num = int(input("Введите число:"))
while True:


  if num > pc:
    print('меньше')
  if num < pc:
    print("больше")
  num = int(input('Your number:'))
  if num == pc:
    print('You win')


    break

"""# Задание 4. Математический спринт
### Суть: Игра на скорость. За отведенное время (например, 60 секунд) нужно решить как можно больше примеров.
Основные требования:
1. Программа генерирует случайные примеры (сложение, вычитание,
умножение).
2. Игрок вводит ответ. Если верно — засчитывается очко и дается следующий пример. Если неверно — пример повторяется или пропускается (на твой выбор).
3. В консоли должно быть видно оставшееся время (или таймер просто работает в фоне).
4. По истечении времени игра останавливается и выводит итоговый счет и статистику (сколько верных/неверных).
"""

# Ваше решение здесь

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
# %config InlineBackend.figure_format = 'retina'

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.sans-serif'] = ['DejaVu Sans', 'Arial', 'Helvetica', 'Segoe UI']
plt.rcParams['axes.unicode_minus'] = False

plt.style.use('seaborn-v0_8-whitegrid')

import random
import time

correct = 0
incorrect = 0
start_time = time.time()

print("Игра началась! У вас 60 секунд.")

while time.time() - start_time < 60:
    a, b = random.randint(1, 10), random.randint(1, 10)
    op = random.choice(["+", "-", "*"])
    user_ans = int(input(f"{a} {op} {b} = "))

    if user_ans == eval(f"{a}{op}{b}"):
        correct += 1
    else:
        incorrect += 1

print(f"\nКонец! Верно: {correct}, Ошибок: {incorrect}")

x = np.linspace(0, 10, 300)
y1 = np.sin(x) * np.exp(-x / 10)
y2 = np.cos(x) * np.exp(-x / 10)

fig, ax = plt.subplots(figsize=(10, 5), dpi=120)

ax.plot(x, y1, color='#FF6B6B', linewidth=2.5, label='Затухающий синус')
ax.plot(x, y2, color='#4ECDC4', linewidth=2.5, label='Затухающий косинус')

ax.fill_between(x, y1, alpha=0.3, color='#FF6B6B')
ax.fill_between(x, y2, alpha=0.3, color='#4ECDC4')

ax.set_title('Затухающие колебания', fontsize=16, fontweight='bold', pad=15)
ax.set_xlabel('Время', fontsize=12)
ax.set_ylabel('Амплитуда', fontsize=12)
ax.legend(fontsize=11, loc='upper right')
ax.grid(True, alpha=0.3)

plt.show()

np.random.seed(42)
n = 200
x = np.random.randn(n)
y = x * 0.8 + np.random.randn(n) * 0.5
colors = np.sqrt(x**2 + y**2)
sizes = np.random.uniform(20, 200, n)

fig, ax = plt.subplots(figsize=(8, 6), dpi=120)

scatter = ax.scatter(x, y, c=colors, s=sizes, cmap='plasma',
                     alpha=0.7, edgecolors='white', linewidth=0.5)

cbar = plt.colorbar(scatter, ax=ax)
cbar.set_label('Расстояние до центра', fontsize=11)

ax.set_title('Распределение точек в 2D', fontsize=16, fontweight='bold')
ax.set_xlabel('Ось X', fontsize=12)
ax.set_ylabel('Ось Y', fontsize=12)
ax.grid(True, alpha=0.3, linestyle='--')

plt.show()

categories = ['Python', 'JavaScript', 'Java', 'C++', 'Rust', 'Go']
values = [85, 78, 65, 55, 45, 50]
colors = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#FFEAA7', '#DDA0DD']

fig, ax = plt.subplots(figsize=(10, 5), dpi=120)

bars = ax.bar(categories, values, color=colors, edgecolor='white',
              linewidth=1.5, width=0.6)

for bar, val in zip(bars, values):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1.5,
            f'{val}%', ha='center', va='bottom', fontsize=12, fontweight='bold')

ax.set_title('Популярность языков программирования', fontsize=16, fontweight='bold', pad=15)
ax.set_ylabel('Индекс популярности', fontsize=12)
ax.set_ylim(0, 100)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.grid(axis='y', alpha=0.3, linestyle='--')

plt.show()

labels = ['Работа', 'Сон', 'Учёба', 'Отдых', 'Еда']
sizes = [8, 8, 4, 2, 2]
colors = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#FFEAA7', '#DDA0DD']

fig, ax = plt.subplots(figsize=(7, 7), dpi=120)

wedges, texts, autotexts = ax.pie(
    sizes, labels=labels, colors=colors,
    autopct='%1.0f%%', startangle=90, pctdistance=0.8,
    wedgeprops=dict(width=0.4, edgecolor='white', linewidth=2)
)

for text in texts:
    text.set_fontsize(12)
for autotext in autotexts:
    autotext.set_color('white')
    autotext.set_fontweight('bold')
    autotext.set_fontsize(11)

ax.text(0, 0, '24 часа\nв сУтках', ha='center', va='center',
        fontsize=16, fontweight='bold', color='#333333')

ax.set_title('Распределение времени', fontsize=18, fontweight='bold', pad=20)
plt.show()

np.random.seed(7)
data = np.random.rand(8, 8)
data = (data + data.T) / 2
np.fill_diagonal(data, 1)

labels = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

fig, ax = plt.subplots(figsize=(8, 6), dpi=120)

sns.heatmap(data, annot=True, fmt='.2f', cmap='viridis',
            xticklabels=labels, yticklabels=labels,
            linewidths=0.5, linecolor='white',
            cbar_kws={'label': 'Значение'}, ax=ax)

ax.set_title('Матрица корреляций', fontsize=16, fontweight='bold', pad=15)
plt.show()